### ISSUE TITLE
v0.4.3 should have been v0.5.0

### ISSUE THREAD

**Issue by iliana** [awslabs/coldsnap#242]
The v0.4.3 release breaks simple use of `cargo update` in crates depending on coldsnap.

This is because to use structs like [`SnapshotUploader`](https://docs.rs/coldsnap/latest/coldsnap/struct.SnapshotUploader.html), you need to pass in an `EbsClient` struct from the aws-sdk-ebs crate. Downstream crates that use the coldsnap library also need to install aws-sdk-ebs. [The version of aws-sdk-ebs was bumped from 0.18 to 0.24](https://github.com/awslabs/coldsnap/compare/v0.4.2...v0.4.3#diff-2e9d962a08321605940b5a657135052fbcef87b5e360662bb527c96d9a615542), which makes the `EbsClient` accepted by `SnapshotUploader::new` a different type, considered [a breaking change](https://doc.rust-lang.org/cargo/reference/semver.html#fn-change-arity).

While this didn't impact me because I was using a git dependency, I recommend yanking v0.4.3 and republishing as v0.5.0.

**Comment by jpculp** [comment]
Thanks for the catch! We have gone ahead and yanked v0.4.3 and republished as v0.5.0.

**Comment by iliana** [comment]
Thanks so much!
