### ISSUE TITLE
Compilation error when installing with Cargo

### ISSUE THREAD

**Issue by jonroop** [awslabs/coldsnap#344]
I installed the latest version of Rust (rustc 1.80.0) and attempted to install Coldsnap using the command provided in the README, i.e.
`$ cargo install --locked coldsnap`

However, I got a compilation error when I did so: `error[E0282]: type annotations needed for 'Box<_>' `
Here is a screenshot:
![image](https://github.com/user-attachments/assets/0d214ccb-a59b-428a-bc86-b1b22ac26655)

As you can see from the screenshot, it seems to error out when compiling the dependency 'rustc_version': 
https://docs.rs/crate/rustc_version/latest

I am using Windows 11, by the way.

**Comment by jonroop** [comment]
Correction: the error occurs while compiling the "time" library. 
The issue is also described over here:
https://users.rust-lang.org/t/time-crate-compilation-error/111789

I tried a couple of commands mentioned in that thread with no luck.

**Comment by jpculp** [comment]
@jonroop, thank you for bringing this to our attention. I'm seeing the same error on Linux and MacOS. We're looking into it, but a workaround is using Rust 1.79.

_ex._ `cargo +1.79 install coldsnap --locked`

**Comment by jpculp** [comment]
It turns out that this was a simple dependency bump. I've gone ahead and cut a **v0.6.2** release, so you should be able to install `coldsnap` without issue now. Let us know if you run into any further issues!
