### ISSUE TITLE
add support for downloading to an existing file

### ISSUE THREAD

**Issue by bcressey** [awslabs/coldsnap#35]
It might be useful to add an option to write a downloaded snapshot directly to a file, such as a block device. That would avoid the need for intermediate storage, trading off safety and correctness checks.

**Comment by webern** [comment]
Pass a flag for this? Names coming to mind aren't great:
- `--no-create-file`
- `--use-existing-file`

**Comment by bcressey** [comment]
Maybe '--in-place' like sed?

**Comment by bcressey** [comment]
In #86 we decided to auto-detect block devices and modify them in place, if given one as a target. So this is no longer needed.
