### ISSUE TITLE
`coldsnap download` hangs on the last ~20 blocks

### ISSUE THREAD

**Issue by btj-fyi** [awslabs/coldsnap#353]
# `coldsnap download` hangs on the last ~20 blocks

I've been trying to download a snapshot using `coldsnap download` but it hangs on the last few blocks every time. Has anyone seen this? It always gets stuck like this, 
```
$ coldsnap download snap-<redacted> /data/RA01-C.img
  Downloading  [=================================================>] 102316/102353 (1s)
```
I checked to see if coldsnap was consuming any CPU or doing anything in memory and it doesn't seem to be once it gets stuck.

I tried on a Debian VM in VirtualBox and an AlmaLinux VM on a Proxmox server. I think it should work just fine in either case but including just in case that is relevant. 

coldsnap = 0.6.2 
aws = 2.17.37

**Comment by ben-kiplot** [comment]
I'm also seeing this issue running on WSL2 (Ubuntu), gets stuck on the last 1-5 blocks  every time

**Comment by btj-fyi** [comment]
Are you by chance running two downloads into the same directory?

**Comment by btj-fyi** [comment]
Running two downloads into the same folder seemed to have been the problem. Trying again one at a time worked just fine.
