### ISSUE TITLE
Snapshot restore : bad superblock

### ISSUE THREAD

**Issue by enitinb** [awslabs/coldsnap#81]
Trying to take the backup of the drive completly for testing purpose. Following issues are appearing 

1. Lets say if we have /dev/xvdf of 5GB it takes only snap of 1GB but does creates the snapshot in aws
2. But when create the volume out of that snapshot and then try to mount get this error

`mount: /data: wrong fs type, bad option, bad superblock on /dev/xvdi, missing codepage or helper program, or other error.`

**Comment by zmrow** [comment]
Thanks for letting us know!  @bertieucbs this seems related to #84 ?

**Comment by enitinb** [comment]
Hi @zmrow - Yes that is correct. Its the same use case.
