### ISSUE TITLE
Support reading and writing to volumes

### ISSUE THREAD

**Issue by padonija** [awslabs/coldsnap#84]
This is a new feature request for coldsnap to support reading and writing to volumes at a block level. coldsnap should support:

1. Creating snapshots from a volume using the raw device name of the volume such as /dev/hdh. This will allow volumes to be backed up to an EBS snapshot.

2. Recovering a snapshot to a volume using the raw device name of the volume such as /dev/hdh. This will allow a volume to be recovered from an EBS snapshot.

**Comment by zmrow** [comment]
Thanks for opening this @padonija ! 

If you have any other additional details around your use case or scenario that you're willing to share that would be great!
